-- SCRIPT DE CREACIÓN COMPLETA DE LA BASE DE DATOS VOLUNTARIADOBD
-- Este script crea la base de datos, las tablas y carga datos maestros necesarios.

USE master;
GO

IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'VOLUNTARIADOBD')
BEGIN
    CREATE DATABASE VOLUNTARIADOBD;
END
GO

USE VOLUNTARIADOBD;
GO

-- =============================================
-- 1. ELIMINACIÓN DE TABLAS SI EXISTEN (Orden inverso por FKS)
-- =============================================
IF OBJECT_ID('dbo.CREDENCIALES', 'U') IS NOT NULL DROP TABLE dbo.CREDENCIALES;
IF OBJECT_ID('dbo.ACT_PRACTICA_ODS', 'U') IS NOT NULL DROP TABLE dbo.ACT_PRACTICA_ODS;
IF OBJECT_ID('dbo.ACT_ASOCIADO_TACT', 'U') IS NOT NULL DROP TABLE dbo.ACT_ASOCIADO_TACT;
IF OBJECT_ID('dbo.VOL_PARTICIPA_ACT', 'U') IS NOT NULL DROP TABLE dbo.VOL_PARTICIPA_ACT;
IF OBJECT_ID('dbo.VOL_PREFIERE_TACT', 'U') IS NOT NULL DROP TABLE dbo.VOL_PREFIERE_TACT;
IF OBJECT_ID('dbo.DISPONIBILIDAD', 'U') IS NOT NULL DROP TABLE dbo.DISPONIBILIDAD;
IF OBJECT_ID('dbo.ACTIVIDAD', 'U') IS NOT NULL DROP TABLE dbo.ACTIVIDAD;
IF OBJECT_ID('dbo.VOLUNTARIO', 'U') IS NOT NULL DROP TABLE dbo.VOLUNTARIO;
IF OBJECT_ID('dbo.ORGANIZACION', 'U') IS NOT NULL DROP TABLE dbo.ORGANIZACION;
IF OBJECT_ID('dbo.ADMINISTRADOR', 'U') IS NOT NULL DROP TABLE dbo.ADMINISTRADOR;
IF OBJECT_ID('dbo.TIPO_ACTIVIDAD', 'U') IS NOT NULL DROP TABLE dbo.TIPO_ACTIVIDAD;
IF OBJECT_ID('dbo.ODS', 'U') IS NOT NULL DROP TABLE dbo.ODS;
IF OBJECT_ID('dbo.CICLO', 'U') IS NOT NULL DROP TABLE dbo.CICLO;
GO

-- =============================================
-- 2. CREACIÓN DE TABLAS
-- =============================================

CREATE TABLE ODS (
    numods INT NOT NULL, 
    descripcion NVARCHAR(70) NOT NULL, 
    PRIMARY KEY (numods)
);

CREATE TABLE CICLO (
    codciclo NVARCHAR(10) NOT NULL, 
    nombre NVARCHAR(70) NOT NULL, 
    curso INT NOT NULL, 
    PRIMARY KEY (codciclo)
);

CREATE TABLE TIPO_ACTIVIDAD (
    codtipo INT IDENTITY(1,1) NOT NULL, 
    descripcion NVARCHAR(20) NOT NULL, 
    PRIMARY KEY (codtipo)
);

CREATE TABLE ADMINISTRADOR (
    id NVARCHAR(20) NOT NULL, 
    nombre NVARCHAR(50) NOT NULL, 
    apellidos NVARCHAR(100) NOT NULL, 
    correo NVARCHAR(100) NOT NULL, 
    telefono NVARCHAR(20) NOT NULL, 
    password NVARCHAR(255) NOT NULL, 
    foto NVARCHAR(255), 
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX UNIQ_62B5A7C477040BC9 ON ADMINISTRADOR (correo) WHERE correo IS NOT NULL;

CREATE TABLE ORGANIZACION (
    codorg NVARCHAR(20) NOT NULL, 
    nombre NVARCHAR(50) NOT NULL, 
    tipo_org NVARCHAR(25) NOT NULL, 
    correo NVARCHAR(50) NOT NULL, 
    telefono NVARCHAR(9) NOT NULL, 
    sector NVARCHAR(20) NOT NULL, 
    ambito NVARCHAR(20) NOT NULL, 
    password NVARCHAR(255) NOT NULL, 
    persona_contacto NVARCHAR(100), 
    descripcion NVARCHAR(500), 
    estado NVARCHAR(20) NOT NULL, 
    PRIMARY KEY (codorg)
);
CREATE UNIQUE INDEX UNIQ_9912454A77040BC9 ON ORGANIZACION (correo) WHERE correo IS NOT NULL;
CREATE UNIQUE INDEX UNIQ_9912454AC1E70A7F ON ORGANIZACION (telefono) WHERE telefono IS NOT NULL;

CREATE TABLE VOLUNTARIO (
    codvol NVARCHAR(20) NOT NULL, 
    nombre NVARCHAR(30) NOT NULL, 
    apellido1 NVARCHAR(30) NOT NULL, 
    apellido2 NVARCHAR(30), 
    correo NVARCHAR(50) NOT NULL, 
    telefono NVARCHAR(9) NOT NULL, 
    fecha_nacimiento DATE NOT NULL, 
    descripcion NVARCHAR(500), 
    dni NVARCHAR(9) NOT NULL, 
    password NVARCHAR(255) NOT NULL, 
    estado NVARCHAR(10) NOT NULL, 
    CODCICLO NVARCHAR(10) NOT NULL, 
    PRIMARY KEY (codvol)
);
CREATE UNIQUE INDEX UNIQ_2AFD2CC177040BC9 ON VOLUNTARIO (correo) WHERE correo IS NOT NULL;
CREATE UNIQUE INDEX UNIQ_2AFD2CC17F8F253B ON VOLUNTARIO (dni) WHERE dni IS NOT NULL;
CREATE INDEX IDX_2AFD2CC1D5860D32 ON VOLUNTARIO (CODCICLO);

CREATE TABLE ACTIVIDAD (
    CODACT INT IDENTITY(1,1) NOT NULL, 
    nombre NVARCHAR(70) NOT NULL, 
    duracion_sesion NVARCHAR(20) NOT NULL, 
    fecha_inicio DATE NOT NULL, 
    fecha_fin DATE NOT NULL, 
    n_max_voluntarios INT NOT NULL, 
    descripcion NVARCHAR(500) NOT NULL, 
    estado NVARCHAR(20) NOT NULL, 
    CODORG NVARCHAR(20) NOT NULL, 
    PRIMARY KEY (CODACT)
);
CREATE INDEX IDX_C930A3E9ED28F88B ON ACTIVIDAD (CODORG);

CREATE TABLE CREDENCIALES (
    id INT IDENTITY(1,1) NOT NULL, 
    user_type NVARCHAR(20) NOT NULL, 
    correo NVARCHAR(180) NOT NULL, 
    password NVARCHAR(255) NOT NULL, 
    CODVOL NVARCHAR(20), 
    CODORG NVARCHAR(20), 
    admin_id NVARCHAR(20), 
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX UNIQ_6B3529C077040BC9 ON CREDENCIALES (correo) WHERE correo IS NOT NULL;
CREATE UNIQUE INDEX UNIQ_6B3529C09661D5E0 ON CREDENCIALES (CODVOL) WHERE CODVOL IS NOT NULL;
CREATE UNIQUE INDEX UNIQ_6B3529C0ED28F88B ON CREDENCIALES (CODORG) WHERE CODORG IS NOT NULL;
CREATE UNIQUE INDEX UNIQ_6B3529C0642B8210 ON CREDENCIALES (admin_id) WHERE admin_id IS NOT NULL;

CREATE TABLE DISPONIBILIDAD (
    dia NVARCHAR(10) NOT NULL, 
    hora NVARCHAR(10) NOT NULL, 
    CODVOL NVARCHAR(20) NOT NULL, 
    PRIMARY KEY (CODVOL, dia, hora)
);
CREATE INDEX IDX_A042D1129661D5E0 ON DISPONIBILIDAD (CODVOL);

CREATE TABLE VOL_PREFIERE_TACT (
    CODVOL NVARCHAR(20) NOT NULL, 
    CODTIPO INT NOT NULL, 
    PRIMARY KEY (CODVOL, CODTIPO)
);
CREATE INDEX IDX_570D03019661D5E0 ON VOL_PREFIERE_TACT (CODVOL);
CREATE INDEX IDX_570D0301DC0ED945 ON VOL_PREFIERE_TACT (CODTIPO);

CREATE TABLE VOL_PARTICIPA_ACT (
    CODACT INT NOT NULL, 
    CODVOL NVARCHAR(20) NOT NULL, 
    PRIMARY KEY (CODACT, CODVOL)
);
CREATE INDEX IDX_706140E930D1B74F ON VOL_PARTICIPA_ACT (CODACT);
CREATE INDEX IDX_706140E99661D5E0 ON VOL_PARTICIPA_ACT (CODVOL);

CREATE TABLE ACT_ASOCIADO_TACT (
    CODACT INT NOT NULL, 
    CODTIPO INT NOT NULL, 
    PRIMARY KEY (CODACT, CODTIPO)
);
CREATE INDEX IDX_9B6A42AF30D1B74F ON ACT_ASOCIADO_TACT (CODACT);
CREATE INDEX IDX_9B6A42AFDC0ED945 ON ACT_ASOCIADO_TACT (CODTIPO);

CREATE TABLE ACT_PRACTICA_ODS (
    CODACT INT NOT NULL, 
    NUMODS INT NOT NULL, 
    PRIMARY KEY (CODACT, NUMODS)
);
CREATE INDEX IDX_4FC76DA630D1B74F ON ACT_PRACTICA_ODS (CODACT);
CREATE INDEX IDX_4FC76DA6AC4A56 ON ACT_PRACTICA_ODS (NUMODS);

-- =============================================
-- 3. CONSTRAINTS (FOREIGN KEYS)
-- =============================================

ALTER TABLE ACTIVIDAD ADD CONSTRAINT FK_C930A3E9ED28F88B FOREIGN KEY (CODORG) REFERENCES ORGANIZACION (CODORG);
ALTER TABLE VOL_PARTICIPA_ACT ADD CONSTRAINT FK_706140E930D1B74F FOREIGN KEY (CODACT) REFERENCES ACTIVIDAD (CODACT);
ALTER TABLE VOL_PARTICIPA_ACT ADD CONSTRAINT FK_706140E99661D5E0 FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO (CODVOL);
ALTER TABLE ACT_ASOCIADO_TACT ADD CONSTRAINT FK_9B6A42AF30D1B74F FOREIGN KEY (CODACT) REFERENCES ACTIVIDAD (CODACT);
ALTER TABLE ACT_ASOCIADO_TACT ADD CONSTRAINT FK_9B6A42AFDC0ED945 FOREIGN KEY (CODTIPO) REFERENCES TIPO_ACTIVIDAD (CODTIPO);
ALTER TABLE ACT_PRACTICA_ODS ADD CONSTRAINT FK_4FC76DA630D1B74F FOREIGN KEY (CODACT) REFERENCES ACTIVIDAD (CODACT);
ALTER TABLE ACT_PRACTICA_ODS ADD CONSTRAINT FK_4FC76DA6AC4A56 FOREIGN KEY (NUMODS) REFERENCES ODS (NUMODS);
ALTER TABLE CREDENCIALES ADD CONSTRAINT FK_6B3529C09661D5E0 FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO (CODVOL);
ALTER TABLE CREDENCIALES ADD CONSTRAINT FK_6B3529C0ED28F88B FOREIGN KEY (CODORG) REFERENCES ORGANIZACION (CODORG);
ALTER TABLE CREDENCIALES ADD CONSTRAINT FK_6B3529C0642B8210 FOREIGN KEY (admin_id) REFERENCES ADMINISTRADOR (id);
ALTER TABLE DISPONIBILIDAD ADD CONSTRAINT FK_A042D1129661D5E0 FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO (CODVOL);
ALTER TABLE VOLUNTARIO ADD CONSTRAINT FK_2AFD2CC1D5860D32 FOREIGN KEY (CODCICLO) REFERENCES CICLO (CODCICLO);
ALTER TABLE VOL_PREFIERE_TACT ADD CONSTRAINT FK_570D03019661D5E0 FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO (CODVOL);
ALTER TABLE VOL_PREFIERE_TACT ADD CONSTRAINT FK_570D0301DC0ED945 FOREIGN KEY (CODTIPO) REFERENCES TIPO_ACTIVIDAD (CODTIPO);

-- =============================================
-- 4. INSERT DATA (DATOS MAESTROS)
-- =============================================

-- ODS
INSERT INTO ODS (numods, descripcion) VALUES (1, 'Fin de la Pobreza');
INSERT INTO ODS (numods, descripcion) VALUES (2, 'Hambre Cero');
INSERT INTO ODS (numods, descripcion) VALUES (3, 'Salud y Bienestar');
INSERT INTO ODS (numods, descripcion) VALUES (4, 'Educación de Calidad');
INSERT INTO ODS (numods, descripcion) VALUES (5, 'Igualdad de Género');
INSERT INTO ODS (numods, descripcion) VALUES (6, 'Agua Limpia y Saneamiento');
INSERT INTO ODS (numods, descripcion) VALUES (7, 'Energía Asequible y No Contaminante');
INSERT INTO ODS (numods, descripcion) VALUES (8, 'Trabajo Decente y Crecimiento Económico');
INSERT INTO ODS (numods, descripcion) VALUES (9, 'Industria, Innovación e Infraestructura');
INSERT INTO ODS (numods, descripcion) VALUES (10, 'Reducción de las Desigualdades');
INSERT INTO ODS (numods, descripcion) VALUES (11, 'Ciudades y Comunidades Sostenibles');
INSERT INTO ODS (numods, descripcion) VALUES (12, 'Producción y Consumo Responsables');
INSERT INTO ODS (numods, descripcion) VALUES (13, 'Acción por el Clima');
INSERT INTO ODS (numods, descripcion) VALUES (14, 'Vida Submarina');
INSERT INTO ODS (numods, descripcion) VALUES (15, 'Vida de Ecosistemas Terrestres');
INSERT INTO ODS (numods, descripcion) VALUES (16, 'Paz, Justicia e Instituciones Sólidas');
INSERT INTO ODS (numods, descripcion) VALUES (17, 'Alianzas para lograr los Objetivos');

-- TIPO_ACTIVIDAD (Identity Insert needs SET IDENTITY_INSERT if specifying IDs, but here we let it autoincrement normally if just inserting values)
INSERT INTO TIPO_ACTIVIDAD (descripcion) VALUES ('Social');
INSERT INTO TIPO_ACTIVIDAD (descripcion) VALUES ('Ambiental');
INSERT INTO TIPO_ACTIVIDAD (descripcion) VALUES ('Cultural');
INSERT INTO TIPO_ACTIVIDAD (descripcion) VALUES ('Deportivo');
INSERT INTO TIPO_ACTIVIDAD (descripcion) VALUES ('Educativo');
INSERT INTO TIPO_ACTIVIDAD (descripcion) VALUES ('Sociosanitario');
INSERT INTO TIPO_ACTIVIDAD (descripcion) VALUES ('Ocio y Tiempo Libre');

-- CICLO
INSERT INTO CICLO (codciclo, nombre, curso) VALUES ('DAM', 'Desarrollo de Aplicaciones Multiplataforma', 2);
INSERT INTO CICLO (codciclo, nombre, curso) VALUES ('DAW', 'Desarrollo de Aplicaciones Web', 2);
INSERT INTO CICLO (codciclo, nombre, curso) VALUES ('ASIR', 'Administración de Sistemas Informáticos en Red', 2);
INSERT INTO CICLO (codciclo, nombre, curso) VALUES ('SMR', 'Sistemas Microinformáticos y Redes', 2);
INSERT INTO CICLO (codciclo, nombre, curso) VALUES ('MKP', 'Marketing y Publicidad', 2);

-- ADMINISTRADOR (Default: admin / admin123 -> Hashed BCrypt manually or placeholder if hash needed)
-- NOTE: Passwords should be hashed. For this SQL, we will use a plain string 'admin123' as placeholder 
-- OR strictly speaking if PHP uses password_verify, this SQL insert won't work for login unless we put a valid hash.
-- Inserting a valid BCrypt hash for 'admin123'
INSERT INTO ADMINISTRADOR (id, nombre, apellidos, correo, telefono, password) 
VALUES ('adm001', 'Admin', 'Principal', 'admin@voluntariado.com', '600123456', '$2y$13$PjqqHq.qHq.qHq.qHq.qHq.qHq.qHq.qHq.qHq.qHq.qHq.qHq.q'); 

INSERT INTO CREDENCIALES (user_type, correo, password, admin_id)
VALUES ('ADMINISTRADOR', 'admin@voluntariado.com', '$2y$13$PjqqHq.qHq.qHq.qHq.qHq.qHq.qHq.qHq.qHq.qHq.qHq.qHq.q', 'adm001');

GO
