CREATE DATABASE VOLUNTARIADOBD
GO


USE VOLUNTARIADOBD
GO

CREATE TABLE ORGANIZACION(
    CODORG SMALLINT IDENTITY(1,1) NOT NULL,
    NOMBRE NVARCHAR(50) NOT NULL,
    TIPO_ORG NVARCHAR(25) NOT NULL,
    CORREO NVARCHAR(50) NOT NULL,
    TELEFONO CHAR(9) NOT NULL,
    SECTOR NVARCHAR(20) NOT NULL,
    AMBITO NVARCHAR(20) NOT NULL,
    DESCRIPCION NVARCHAR(500),

    -- CONSTRAINTS
    CONSTRAINT PK_ORGANIZACION PRIMARY KEY (CODORG),
    CONSTRAINT UQ_ORGANIZACION_CORREO UNIQUE (CORREO),
    CONSTRAINT UQ_ORGANIZACION_TELEFONO UNIQUE (TELEFONO),
    CONSTRAINT CK_ORGANIZACION_TIPO_ORG CHECK(TIPO_ORG IN ('ONG', 'FUNDACION', 'ASOCIACION', 'ENTIDAD P�BLICA', 'OTRA')),
    CONSTRAINT CK_ORGANIZACION_SECTOR CHECK(SECTOR IN ('SOCIAL', 'SALUD', 'EDUCATIVO', 'AMBIENTAL', 'CULTURAL', 'DEPORTIVO', 'TECNOL�GICO', 'OTRO')),
    CONSTRAINT CK_ORGANIZACION_AMBITO CHECK(AMBITO IN ('LOCAL', 'REGIONAL', 'NACIONAL', 'INTERNACIONAL')),
    CONSTRAINT CK_ORGANIZACION_TELEFONO CHECK(TELEFONO LIKE '[6-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    CONSTRAINT CK_ORGANIZACION_CORREO CHECK(CORREO LIKE '%@%.%')
)
GO

CREATE INDEX IX_ORGANIZACION_NOMBRE ON ORGANIZACION(NOMBRE)
GO


CREATE TABLE ACTIVIDAD(
    CODACT SMALLINT IDENTITY(1,1) NOT NULL,
    NOMBRE NVARCHAR(70) NOT NULL,
    DURACION_SESION TIME NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    N_MAX_VOLUNTARIOS SMALLINT NOT NULL,
    CODORG SMALLINT NOT NULL,
    DESCRIPCION NVARCHAR(500) NOT NULL,

    -- CONSTRAINTS
    CONSTRAINT PK_ACTIVIDAD PRIMARY KEY (CODACT),
    CONSTRAINT FK_ACTIVIDAD_ORGANIZACION FOREIGN KEY (CODORG) REFERENCES ORGANIZACION(CODORG),
    CONSTRAINT CK_ACTIVIDAD_FECHAS CHECK(FECHA_FIN >= FECHA_INICIO),
    CONSTRAINT CK_ACTIVIDAD_MAX_VOLUNTARIOS CHECK(N_MAX_VOLUNTARIOS > 0)
)
GO
CREATE UNIQUE INDEX IX_ACTIVIDAD_NOMBRE ON ACTIVIDAD(NOMBRE)
CREATE INDEX IX_ACTIVIDAD_CODORG ON ACTIVIDAD(CODORG)

GO


CREATE TABLE ODS(
    NUMODS SMALLINT NOT NULL,
    DESCRIPCION NVARCHAR(70) NOT NULL,
    CONSTRAINT PK_ODS PRIMARY KEY (NUMODS)
)
GO


CREATE TABLE TIPO_ACTIVIDAD(
    CODTIPO SMALLINT IDENTITY(1,1) NOT NULL,
    DESCRIPCION NVARCHAR(20) NOT NULL,
    CONSTRAINT PK_TIPO_ACTIVIDAD PRIMARY KEY (CODTIPO)

	
)
GO

CREATE UNIQUE INDEX IX_TIPO_ACTIVIDAD_DESCRIPCION ON TIPO_ACTIVIDAD(DESCRIPCION)

CREATE TABLE CICLO(
    CODCICLO NVARCHAR(10) NOT NULL,
    NOMBRE NVARCHAR(70) NOT NULL,
    CURSO SMALLINT NOT NULL,

    -- CONSTRAINTS
    CONSTRAINT PK_CICLO PRIMARY KEY (CODCICLO),
    CONSTRAINT CK_CICLO_CURSO CHECK(CURSO > 0)
)
GO

CREATE INDEX IX_CICLO_NOMBRE_CURSO ON CICLO(NOMBRE, CURSO)
GO


CREATE TABLE VOLUNTARIO(
    CODVOL SMALLINT IDENTITY(1,1) NOT NULL,
    NOMBRE NVARCHAR(30) NOT NULL,
    APELLIDO1 NVARCHAR(30) NOT NULL,
    APELLIDO2 NVARCHAR(30),
    CORREO NVARCHAR(50) NOT NULL,
    TELEFONO CHAR(9) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    DESCRIPCION NVARCHAR(500),
    CODCICLO NVARCHAR(10) NOT NULL,

    -- CONSTRAINT
    CONSTRAINT PK_VOLUNTARIO PRIMARY KEY (CODVOL),
    CONSTRAINT UQ_VOLUNTARIO_CORREO UNIQUE (CORREO),
    CONSTRAINT FK_VOLUNTARIO_CICLO FOREIGN KEY (CODCICLO) REFERENCES CICLO(CODCICLO),
    CONSTRAINT CK_VOLUNTARIO_FECHA_NACIMIENTO CHECK(FECHA_NACIMIENTO <= GETDATE()),
    CONSTRAINT CK_VOLUNTARIO_TELEFONO CHECK(TELEFONO LIKE '[6-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
    CONSTRAINT CK_VOLUNTARIO_CORREO CHECK(CORREO LIKE '%@%.%')
)
GO

CREATE INDEX IX_VOLUNTARIO_CICLO_NOMBRE ON VOLUNTARIO(CODCICLO, NOMBRE, APELLIDO1, APELLIDO2)
GO


CREATE TABLE DISPONIBILIDAD(
    CODVOL SMALLINT NOT NULL,
    DIA NVARCHAR(10) NOT NULL,
    HORA NVARCHAR(10) NOT NULL,

    -- CONSTRAINTS
    CONSTRAINT PK_DISPONIBILIDAD PRIMARY KEY (CODVOL, DIA, HORA),
    CONSTRAINT FK_DISPONIBILIDAD_VOLUNTARIO FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO(CODVOL),
    CONSTRAINT CK_DISPONIBILIDAD_DIA CHECK(DIA IN ('LUNES','MARTES','MI�RCOLES','JUEVES','VIERNES','S�BADO','DOMINGO')),
    CONSTRAINT CK_DISPONIBILIDAD_HORA CHECK(HORA IN ('3-4', '4-5', '5-6', '6-7', '7-8', '8-9', '9-10'))
)
GO


CREATE TABLE ACT_ASOCIADO_TACT(
    CODACT SMALLINT NOT NULL,
    CODTIPO SMALLINT NOT NULL,

    -- CONSTRAINTS
    CONSTRAINT PK_ACT_ASOCIADO_TACT PRIMARY KEY (CODACT, CODTIPO),
    CONSTRAINT FK_ACT_ASOCIADO_TACT_ACTIVIDAD FOREIGN KEY (CODACT) REFERENCES ACTIVIDAD(CODACT),
    CONSTRAINT FK_ACT_ASOCIADO_TACT_TIPO FOREIGN KEY (CODTIPO) REFERENCES TIPO_ACTIVIDAD(CODTIPO)
)
GO


CREATE TABLE VOL_PARTICIPA_ACT(
    CODVOL SMALLINT NOT NULL,
    CODACT SMALLINT NOT NULL,

    -- CONSTRAINTS
    CONSTRAINT PK_VOL_PARTICIPA_ACT PRIMARY KEY (CODVOL, CODACT),
    CONSTRAINT FK_VOL_PARTICIPA_ACT_VOLUNTARIO FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO(CODVOL),
    CONSTRAINT FK_VOL_PARTICIPA_ACT_ACTIVIDAD FOREIGN KEY (CODACT) REFERENCES ACTIVIDAD(CODACT)
)
GO


CREATE TABLE VOL_PREFIERE_TACT(
    CODVOL SMALLINT NOT NULL,
    CODTIPO SMALLINT NOT NULL,

    -- CONSTRAINTS
    CONSTRAINT PK_VOL_PREFIERE_TACT PRIMARY KEY (CODVOL, CODTIPO),
    CONSTRAINT FK_VOL_PREFIERE_TACT_VOLUNTARIO FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO(CODVOL),
    CONSTRAINT FK_VOL_PREFIERE_TACT_TIPO FOREIGN KEY (CODTIPO) REFERENCES TIPO_ACTIVIDAD(CODTIPO)
)
GO


CREATE TABLE ACT_PRACTICA_ODS(
    CODACT SMALLINT NOT NULL,
    NUMODS SMALLINT NOT NULL,

    CONSTRAINT PK_ACT_PRACTICA_ODS PRIMARY KEY (CODACT, NUMODS),
    CONSTRAINT FK_ACT_PRACTICA_ODS_ACTIVIDAD FOREIGN KEY (CODACT) REFERENCES ACTIVIDAD(CODACT),
    CONSTRAINT FK_ACT_PRACTICA_ODS_ODS FOREIGN KEY (NUMODS) REFERENCES ODS(NUMODS)
)

