<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260123153655 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ACTIVIDAD (CODACT INT IDENTITY NOT NULL, nombre NVARCHAR(70) NOT NULL, duracion_sesion NVARCHAR(20) NOT NULL, fecha_inicio DATE NOT NULL, fecha_fin DATE NOT NULL, n_max_voluntarios INT NOT NULL, descripcion NVARCHAR(500) NOT NULL, estado NVARCHAR(20) NOT NULL, ubicacion NVARCHAR(255), imagen NVARCHAR(255), CODORG NVARCHAR(20) NOT NULL, PRIMARY KEY (CODACT))');
        $this->addSql('CREATE INDEX IDX_C930A3E9ED28F88B ON ACTIVIDAD (CODORG)');
        $this->addSql('CREATE TABLE VOL_PARTICIPA_ACT (CODACT INT NOT NULL, CODVOL NVARCHAR(20) NOT NULL, PRIMARY KEY (CODACT, CODVOL))');
        $this->addSql('CREATE INDEX IDX_706140E930D1B74F ON VOL_PARTICIPA_ACT (CODACT)');
        $this->addSql('CREATE INDEX IDX_706140E99661D5E0 ON VOL_PARTICIPA_ACT (CODVOL)');
        $this->addSql('CREATE TABLE ACT_ASOCIADO_TACT (CODACT INT NOT NULL, CODTIPO INT NOT NULL, PRIMARY KEY (CODACT, CODTIPO))');
        $this->addSql('CREATE INDEX IDX_9B6A42AF30D1B74F ON ACT_ASOCIADO_TACT (CODACT)');
        $this->addSql('CREATE INDEX IDX_9B6A42AFDC0ED945 ON ACT_ASOCIADO_TACT (CODTIPO)');
        $this->addSql('CREATE TABLE ACT_PRACTICA_ODS (CODACT INT NOT NULL, NUMODS INT NOT NULL, PRIMARY KEY (CODACT, NUMODS))');
        $this->addSql('CREATE INDEX IDX_4FC76DA630D1B74F ON ACT_PRACTICA_ODS (CODACT)');
        $this->addSql('CREATE INDEX IDX_4FC76DA6AC4A56 ON ACT_PRACTICA_ODS (NUMODS)');
        $this->addSql('CREATE TABLE ADMINISTRADOR (id NVARCHAR(20) NOT NULL, nombre NVARCHAR(50) NOT NULL, apellidos NVARCHAR(100) NOT NULL, correo NVARCHAR(100) NOT NULL, telefono NVARCHAR(20) NOT NULL, firebase_uid NVARCHAR(128), avatar NVARCHAR(255), PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_62B5A7C477040BC9 ON ADMINISTRADOR (correo) WHERE correo IS NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_62B5A7C42FB49151 ON ADMINISTRADOR (firebase_uid) WHERE firebase_uid IS NOT NULL');
        $this->addSql('CREATE TABLE CICLO (CODCICLO NVARCHAR(10) NOT NULL, nombre NVARCHAR(70) NOT NULL, curso INT NOT NULL, PRIMARY KEY (CODCICLO))');
        $this->addSql('CREATE TABLE CREDENCIALES (id INT IDENTITY NOT NULL, user_type NVARCHAR(20) NOT NULL, correo NVARCHAR(180) NOT NULL, password NVARCHAR(255) NOT NULL, CODVOL NVARCHAR(20), CODORG NVARCHAR(20), CODADMIN NVARCHAR(20), PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6B3529C09661D5E0 ON CREDENCIALES (CODVOL) WHERE CODVOL IS NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6B3529C0ED28F88B ON CREDENCIALES (CODORG) WHERE CODORG IS NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6B3529C05DC26F56 ON CREDENCIALES (CODADMIN) WHERE CODADMIN IS NOT NULL');
        $this->addSql('CREATE TABLE DISPONIBILIDAD (dia NVARCHAR(10) NOT NULL, NUM_HORAS INT NOT NULL, hora NVARCHAR(10), CODVOL NVARCHAR(20) NOT NULL, PRIMARY KEY (CODVOL, dia))');
        $this->addSql('CREATE INDEX IDX_A042D1129661D5E0 ON DISPONIBILIDAD (CODVOL)');
        $this->addSql('CREATE TABLE ODS (NUMODS INT NOT NULL, descripcion NVARCHAR(70) NOT NULL, PRIMARY KEY (NUMODS))');
        $this->addSql('CREATE TABLE ORGANIZACION (CODORG NVARCHAR(20) NOT NULL, nombre NVARCHAR(50) NOT NULL, tipo_org NVARCHAR(25) NOT NULL, correo NVARCHAR(50) NOT NULL, telefono CHAR(9), sector NVARCHAR(20) NOT NULL, ambito NVARCHAR(20) NOT NULL, firebase_uid NVARCHAR(128), persona_contacto NVARCHAR(100), descripcion NVARCHAR(500), estado NVARCHAR(20) NOT NULL, avatar NVARCHAR(255), direccion NVARCHAR(255), web NVARCHAR(255), PRIMARY KEY (CODORG))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9912454A77040BC9 ON ORGANIZACION (correo) WHERE correo IS NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9912454AC1E70A7F ON ORGANIZACION (telefono) WHERE telefono IS NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9912454A2FB49151 ON ORGANIZACION (firebase_uid) WHERE firebase_uid IS NOT NULL');
        $this->addSql('CREATE TABLE SOLICITUD (id INT IDENTITY NOT NULL, status NVARCHAR(20) NOT NULL, fecha_solicitud DATETIME2(6) NOT NULL, mensaje VARCHAR(MAX), CODVOL NVARCHAR(20) NOT NULL, CODACT INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D210622F9661D5E0 ON SOLICITUD (CODVOL)');
        $this->addSql('CREATE INDEX IDX_D210622F30D1B74F ON SOLICITUD (CODACT)');
        $this->addSql('CREATE TABLE TIPO_ACTIVIDAD (CODTIPO INT IDENTITY NOT NULL, descripcion NVARCHAR(20) NOT NULL, PRIMARY KEY (CODTIPO))');
        $this->addSql('CREATE TABLE VOLUNTARIO (CODVOL NVARCHAR(20) NOT NULL, nombre NVARCHAR(30) NOT NULL, apellido1 NVARCHAR(30) NOT NULL, apellido2 NVARCHAR(30), correo NVARCHAR(50) NOT NULL, telefono CHAR(9), fecha_nacimiento DATE NOT NULL, descripcion NVARCHAR(500), dni CHAR(9), firebase_uid NVARCHAR(128), estado NVARCHAR(10) NOT NULL, avatar NVARCHAR(255), CODCICLO NVARCHAR(10) NOT NULL, PRIMARY KEY (CODVOL))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2AFD2CC177040BC9 ON VOLUNTARIO (correo) WHERE correo IS NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2AFD2CC17F8F253B ON VOLUNTARIO (dni) WHERE dni IS NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2AFD2CC12FB49151 ON VOLUNTARIO (firebase_uid) WHERE firebase_uid IS NOT NULL');
        $this->addSql('CREATE INDEX IDX_2AFD2CC1D5860D32 ON VOLUNTARIO (CODCICLO)');
        $this->addSql('CREATE TABLE VOL_PREFIERE_TACT (CODVOL NVARCHAR(20) NOT NULL, CODTIPO INT NOT NULL, PRIMARY KEY (CODVOL, CODTIPO))');
        $this->addSql('CREATE INDEX IDX_570D03019661D5E0 ON VOL_PREFIERE_TACT (CODVOL)');
        $this->addSql('CREATE INDEX IDX_570D0301DC0ED945 ON VOL_PREFIERE_TACT (CODTIPO)');
        $this->addSql('ALTER TABLE ACTIVIDAD ADD CONSTRAINT FK_C930A3E9ED28F88B FOREIGN KEY (CODORG) REFERENCES ORGANIZACION (CODORG)');
        $this->addSql('ALTER TABLE VOL_PARTICIPA_ACT ADD CONSTRAINT FK_706140E930D1B74F FOREIGN KEY (CODACT) REFERENCES ACTIVIDAD (CODACT)');
        $this->addSql('ALTER TABLE VOL_PARTICIPA_ACT ADD CONSTRAINT FK_706140E99661D5E0 FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO (CODVOL)');
        $this->addSql('ALTER TABLE ACT_ASOCIADO_TACT ADD CONSTRAINT FK_9B6A42AF30D1B74F FOREIGN KEY (CODACT) REFERENCES ACTIVIDAD (CODACT)');
        $this->addSql('ALTER TABLE ACT_ASOCIADO_TACT ADD CONSTRAINT FK_9B6A42AFDC0ED945 FOREIGN KEY (CODTIPO) REFERENCES TIPO_ACTIVIDAD (CODTIPO)');
        $this->addSql('ALTER TABLE ACT_PRACTICA_ODS ADD CONSTRAINT FK_4FC76DA630D1B74F FOREIGN KEY (CODACT) REFERENCES ACTIVIDAD (CODACT)');
        $this->addSql('ALTER TABLE ACT_PRACTICA_ODS ADD CONSTRAINT FK_4FC76DA6AC4A56 FOREIGN KEY (NUMODS) REFERENCES ODS (NUMODS)');
        $this->addSql('ALTER TABLE CREDENCIALES ADD CONSTRAINT FK_6B3529C09661D5E0 FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO (CODVOL)');
        $this->addSql('ALTER TABLE CREDENCIALES ADD CONSTRAINT FK_6B3529C0ED28F88B FOREIGN KEY (CODORG) REFERENCES ORGANIZACION (CODORG)');
        $this->addSql('ALTER TABLE CREDENCIALES ADD CONSTRAINT FK_6B3529C05DC26F56 FOREIGN KEY (CODADMIN) REFERENCES ADMINISTRADOR (id)');
        $this->addSql('ALTER TABLE DISPONIBILIDAD ADD CONSTRAINT FK_A042D1129661D5E0 FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO (CODVOL)');
        $this->addSql('ALTER TABLE SOLICITUD ADD CONSTRAINT FK_D210622F9661D5E0 FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO (CODVOL)');
        $this->addSql('ALTER TABLE SOLICITUD ADD CONSTRAINT FK_D210622F30D1B74F FOREIGN KEY (CODACT) REFERENCES ACTIVIDAD (CODACT)');
        $this->addSql('ALTER TABLE VOLUNTARIO ADD CONSTRAINT FK_2AFD2CC1D5860D32 FOREIGN KEY (CODCICLO) REFERENCES CICLO (CODCICLO)');
        $this->addSql('ALTER TABLE VOL_PREFIERE_TACT ADD CONSTRAINT FK_570D03019661D5E0 FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO (CODVOL)');
        $this->addSql('ALTER TABLE VOL_PREFIERE_TACT ADD CONSTRAINT FK_570D0301DC0ED945 FOREIGN KEY (CODTIPO) REFERENCES TIPO_ACTIVIDAD (CODTIPO)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA db_accessadmin');
        $this->addSql('CREATE SCHEMA db_backupoperator');
        $this->addSql('CREATE SCHEMA db_datareader');
        $this->addSql('CREATE SCHEMA db_datawriter');
        $this->addSql('CREATE SCHEMA db_ddladmin');
        $this->addSql('CREATE SCHEMA db_denydatareader');
        $this->addSql('CREATE SCHEMA db_denydatawriter');
        $this->addSql('CREATE SCHEMA db_owner');
        $this->addSql('CREATE SCHEMA db_securityadmin');
        $this->addSql('ALTER TABLE ACTIVIDAD DROP CONSTRAINT FK_C930A3E9ED28F88B');
        $this->addSql('ALTER TABLE VOL_PARTICIPA_ACT DROP CONSTRAINT FK_706140E930D1B74F');
        $this->addSql('ALTER TABLE VOL_PARTICIPA_ACT DROP CONSTRAINT FK_706140E99661D5E0');
        $this->addSql('ALTER TABLE ACT_ASOCIADO_TACT DROP CONSTRAINT FK_9B6A42AF30D1B74F');
        $this->addSql('ALTER TABLE ACT_ASOCIADO_TACT DROP CONSTRAINT FK_9B6A42AFDC0ED945');
        $this->addSql('ALTER TABLE ACT_PRACTICA_ODS DROP CONSTRAINT FK_4FC76DA630D1B74F');
        $this->addSql('ALTER TABLE ACT_PRACTICA_ODS DROP CONSTRAINT FK_4FC76DA6AC4A56');
        $this->addSql('ALTER TABLE CREDENCIALES DROP CONSTRAINT FK_6B3529C09661D5E0');
        $this->addSql('ALTER TABLE CREDENCIALES DROP CONSTRAINT FK_6B3529C0ED28F88B');
        $this->addSql('ALTER TABLE CREDENCIALES DROP CONSTRAINT FK_6B3529C05DC26F56');
        $this->addSql('ALTER TABLE DISPONIBILIDAD DROP CONSTRAINT FK_A042D1129661D5E0');
        $this->addSql('ALTER TABLE SOLICITUD DROP CONSTRAINT FK_D210622F9661D5E0');
        $this->addSql('ALTER TABLE SOLICITUD DROP CONSTRAINT FK_D210622F30D1B74F');
        $this->addSql('ALTER TABLE VOLUNTARIO DROP CONSTRAINT FK_2AFD2CC1D5860D32');
        $this->addSql('ALTER TABLE VOL_PREFIERE_TACT DROP CONSTRAINT FK_570D03019661D5E0');
        $this->addSql('ALTER TABLE VOL_PREFIERE_TACT DROP CONSTRAINT FK_570D0301DC0ED945');
        $this->addSql('DROP TABLE ACTIVIDAD');
        $this->addSql('DROP TABLE VOL_PARTICIPA_ACT');
        $this->addSql('DROP TABLE ACT_ASOCIADO_TACT');
        $this->addSql('DROP TABLE ACT_PRACTICA_ODS');
        $this->addSql('DROP TABLE ADMINISTRADOR');
        $this->addSql('DROP TABLE CICLO');
        $this->addSql('DROP TABLE CREDENCIALES');
        $this->addSql('DROP TABLE DISPONIBILIDAD');
        $this->addSql('DROP TABLE ODS');
        $this->addSql('DROP TABLE ORGANIZACION');
        $this->addSql('DROP TABLE SOLICITUD');
        $this->addSql('DROP TABLE TIPO_ACTIVIDAD');
        $this->addSql('DROP TABLE VOLUNTARIO');
        $this->addSql('DROP TABLE VOL_PREFIERE_TACT');
    }
}
