<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260113132416 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Links Credentials to User Tables via specific Foreign Keys and migrates data from user_id.';
    }

    public function up(Schema $schema): void
    {
        // 1. Add Nullable FK Columns
        $this->addSql('ALTER TABLE CREDENCIALES ADD CODVOL NVARCHAR(20)');
        $this->addSql('ALTER TABLE CREDENCIALES ADD CODORG NVARCHAR(20)');
        $this->addSql('ALTER TABLE CREDENCIALES ADD admin_id NVARCHAR(20)');
        
        // 2. Data Migration: Transfer user_id to specific columns based on Type
        $this->addSql("UPDATE CREDENCIALES SET CODVOL = user_id WHERE user_type = 'VOLUNTARIO'");
        $this->addSql("UPDATE CREDENCIALES SET CODORG = user_id WHERE user_type = 'ORGANIZACION'");
        $this->addSql("UPDATE CREDENCIALES SET admin_id = user_id WHERE user_type = 'ADMINISTRADOR'");
        
        // 3. Drop old generic column and index
        $this->addSql('DROP INDEX IDX_CRED_USERID ON CREDENCIALES');
        $this->addSql('ALTER TABLE CREDENCIALES DROP COLUMN user_id');

        // 4. Add Constraints and Indices
        $this->addSql('ALTER TABLE CREDENCIALES ADD CONSTRAINT FK_6B3529C09661D5E0 FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO (CODVOL)');
        $this->addSql('ALTER TABLE CREDENCIALES ADD CONSTRAINT FK_6B3529C0ED28F88B FOREIGN KEY (CODORG) REFERENCES ORGANIZACION (CODORG)');
        $this->addSql('ALTER TABLE CREDENCIALES ADD CONSTRAINT FK_6B3529C0642B8210 FOREIGN KEY (admin_id) REFERENCES ADMINISTRADOR (id)');
        
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6B3529C09661D5E0 ON CREDENCIALES (CODVOL) WHERE CODVOL IS NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6B3529C0ED28F88B ON CREDENCIALES (CODORG) WHERE CODORG IS NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6B3529C0642B8210 ON CREDENCIALES (admin_id) WHERE admin_id IS NOT NULL');

        // Other Doctrine generated changes (Indices tidying etc)
        // Check if these exist first before dropping to avoid errors if re-running or if state differs slightly
         // Indices generated by previous migration state but might not exist if manually adjusted. 
         // Safest is to wrap in checks but for generated ones usually safe to leave or wrap block.
         // Given previous robust migration, let's keep it simple but safe.
         
        // CICLO Index
        $this->addSql("IF EXISTS (SELECT * FROM sys.indexes WHERE name='IX_CICLO_NOMBRE_CURSO' AND object_id = OBJECT_ID('CICLO')) DROP INDEX IX_CICLO_NOMBRE_CURSO ON CICLO");
        
        // ORGANIZACION Index
        $this->addSql("IF EXISTS (SELECT * FROM sys.indexes WHERE name='IX_ORGANIZACION_NOMBRE' AND object_id = OBJECT_ID('ORGANIZACION')) DROP INDEX IX_ORGANIZACION_NOMBRE ON ORGANIZACION");
        
        // TIPO_ACTIVIDAD Index
        $this->addSql("IF EXISTS (SELECT * FROM sys.indexes WHERE name='IX_TIPO_ACTIVIDAD_DESCRIPCION' AND object_id = OBJECT_ID('TIPO_ACTIVIDAD')) DROP INDEX IX_TIPO_ACTIVIDAD_DESCRIPCION ON TIPO_ACTIVIDAD");

        // VOLUNTARIO Index
        $this->addSql("IF EXISTS (SELECT * FROM sys.indexes WHERE name='IX_VOLUNTARIO_CICLO_NOMBRE' AND object_id = OBJECT_ID('VOLUNTARIO')) DROP INDEX IX_VOLUNTARIO_CICLO_NOMBRE ON VOLUNTARIO");
        
        // VOL_PREFIERE_TACT Rename
         $this->addSql("IF EXISTS (SELECT * FROM sys.indexes WHERE name='idx_vol_pref_tipo' AND object_id = OBJECT_ID('VOL_PREFIERE_TACT')) EXEC [sp_rename] N'VOL_PREFIERE_TACT.idx_vol_pref_tipo', N'IDX_570D0301DC0ED945', N'INDEX'");

    }

    public function down(Schema $schema): void
    {
        $this->throwIrreversibleMigrationException('Reverting this migration requires complex data restoration logic for user_id which is not implemented.');
    }
}
