<?php

namespace App\EventSubscriber;

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\HttpFoundation\JsonResponse;
use App\Repository\VolunteerRepository;
use App\Repository\OrganizationRepository;
use App\Repository\AdministratorRepository;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;


class ApiSecuritySubscriber implements EventSubscriberInterface
{
    private $volunteerRepository;
    private $organizationRepository;
    private $adminRepository;

    public function __construct(
        VolunteerRepository $volunteerRepository, 
        OrganizationRepository $organizationRepository, 
        AdministratorRepository $adminRepository,
        private ParameterBagInterface $params
    )
    {
        $this->volunteerRepository = $volunteerRepository;
        $this->organizationRepository = $organizationRepository;
        $this->adminRepository = $adminRepository;
    }


    public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::REQUEST => 'onKernelRequest',
        ];
    }

    public function onKernelRequest(RequestEvent $event): void
    {
        $request = $event->getRequest();
        $path = $request->getPathInfo();

        // Only secure /api routes
        if (!str_starts_with($path, '/api')) {
            return;
        }

        // Whitelist public routes
        // Adjust these paths based on actual usage
        $publicRoutes = [
            '/api/login',
            '/api/register',
            '/api/register/organization', // If exists
            '/api/doc', // If swagger is added later
            '/api/ciclos',
            '/api/activity-types',
            '/api/ods',
        ];

        if (in_array($path, $publicRoutes)) {
            return;
        }

        // Allow POST to registration endpoints (same path as authenticated GET)
        $publicPostRoutes = [
            '/api/volunteers',
            '/api/organizations',
        ];

        if ($request->getMethod() === 'POST' && in_array($path, $publicPostRoutes)) {
            return;
        }
        
        // Also allow OPTIONS requests for CORS (handled by Nelmio, but good to be safe)
        if ($request->getMethod() === 'OPTIONS') {
            return;
        }

        // Check Authorization Header
        if (!$request->headers->has('Authorization')) {
            $event->setResponse(new JsonResponse(['error' => 'Authentication required'], 401));
            return;
        }

        $authHeader = $request->headers->get('Authorization');
        if (!str_starts_with($authHeader, 'Bearer ')) {
            $event->setResponse(new JsonResponse(['error' => 'Invalid token format'], 401));
            return;
        }

        $token = substr($authHeader, 7);

        // Validate Token (Manual JWT Decode and Verify)
        try {
            $tokenParts = explode('.', $token);
            if (count($tokenParts) !== 3) {
                 throw new \Exception('Invalid token structure');
            }

            $header = $tokenParts[0];
            $payloadEncoded = $tokenParts[1];
            $signatureProvided = $tokenParts[2];

            // Verify Signature
            $secret = $this->params->get('kernel.secret');
            $expectedSignature = hash_hmac('sha256', "$header.$payloadEncoded", $secret, true);
            $expectedSignatureEncoded = str_replace(['+', '/', '='], ['-', '_', ''], base64_encode($expectedSignature));

            if ($signatureProvided !== $expectedSignatureEncoded) {
                $event->setResponse(new JsonResponse(['error' => 'Invalid token signature'], 401));
                return;
            }

            $payload = json_decode(base64_decode(str_replace(['-', '_'], ['+', '/'], $payloadEncoded)), true);

            if (!$payload) {
                throw new \Exception('Invalid token payload');
            }

            // Expiry check
            if (isset($payload['exp']) && $payload['exp'] < time()) {
                throw new \Exception('Token expired');
            }


            $uid = $payload['sub'] ?? ($payload['user_id'] ?? null);
            if (!$uid) {
                throw new \Exception('Token missing UID');
            }

            // Optional: User existence check
            // For now, if valid firebase UID format, we accept. 
            // Better security: check if user exists in DB.
            
            $userExists = false;
            if ($this->volunteerRepository->findOneBy(['firebaseUid' => $uid])) $userExists = true;
            elseif ($this->organizationRepository->findOneBy(['firebaseUid' => $uid])) $userExists = true;
            elseif ($this->adminRepository->findOneBy(['firebaseUid' => $uid])) $userExists = true;

            // Fallback: Check for prefixed UIDs generated by AuthController for SQL users
            if (!$userExists) {
                if (str_starts_with($uid, 'admin-')) {
                    $id = substr($uid, 6);
                    // Allow adm001 fallback explicitly if not found in DB but is the default admin
                    if ($this->adminRepository->find($id) || $id === 'adm001') {
                        $userExists = true;
                    }
                } elseif (str_starts_with($uid, 'vol-')) {
                    $id = substr($uid, 4);
                    if ($this->volunteerRepository->find($id)) {
                         $userExists = true;
                    }
                } elseif (str_starts_with($uid, 'org-')) {
                     $id = substr($uid, 4);
                     if ($this->organizationRepository->find($id)) {
                         $userExists = true;
                     }
                }
            }

            if (!$userExists) {
                // If checking DB, uncomment below:
                // throw new \Exception('User not found');
                
                // For now, allowing if token is valid structure to avoid blocking valid firebase users not yet synced? 
                // No, security requirement implies we should check.
                // But wait, Register endpoint creates the user. Subsequent requests have token.
                // So user SHOULD exist.
                
                // If it's a new user trying to register, they hit /api/register (public).
                // So valid users hitting other endpoints MUST exist.
                // Log the missing user for debugging
                 error_log('ApiSecuritySubscriber: User not found for UID: ' . $uid);
                 $event->setResponse(new JsonResponse(['error' => 'User not found or invalid token', 'debug_uid' => $uid], 401));
                 return;
            }

            // Attach user info to request
            $request->attributes->set('api_user', true);
            
            // Determine Role and Object
            $userObject = null;
            $role = 'unknown';

            if (str_starts_with($uid, 'admin-')) {
                $userObject = $this->adminRepository->find(substr($uid, 6)) ?? $this->adminRepository->find('adm001');
                $role = 'admin';
            } elseif (str_starts_with($uid, 'vol-')) {
                $userObject = $this->volunteerRepository->find(substr($uid, 4));
                $role = 'volunteer';
            } elseif (str_starts_with($uid, 'org-')) {
                $userObject = $this->organizationRepository->find(substr($uid, 4));
                $role = 'organization';
            } else {
                // Firebase UID lookup - find which repository has this UID
                $vol = $this->volunteerRepository->findOneBy(['firebaseUid' => $uid]);
                if ($vol) {
                    $userObject = $vol;
                    $role = 'volunteer';
                } else {
                    $org = $this->organizationRepository->findOneBy(['firebaseUid' => $uid]);
                    if ($org) {
                        $userObject = $org;
                        $role = 'organization';
                    } else {
                        $admin = $this->adminRepository->findOneBy(['firebaseUid' => $uid]);
                        if ($admin) {
                            $userObject = $admin;
                            $role = 'admin';
                        }
                    }
                }
            }

            $request->attributes->set('api_user_role', $role);
            
            if ($userObject) {
                $request->attributes->set('authenticated_user', $userObject);
            }


        } catch (\Exception $e) {
            error_log('ApiSecuritySubscriber 401 Error: ' . $e->getMessage());
            $event->setResponse(new JsonResponse(['error' => 'Unauthorized: ' . $e->getMessage()], 401));
        }
    }
}
