USE VOLUNTARIADOBD;
GO

-- Añadir columna id_admin si no existe
IF NOT EXISTS(SELECT * FROM sys.columns WHERE Name = N'id_admin' AND Object_ID = Object_ID(N'CREDENCIALES'))
BEGIN
    ALTER TABLE CREDENCIALES ADD id_admin nvarchar(20) NULL;
    PRINT 'Columna id_admin añadida a CREDENCIALES';
END

-- Añadir Constraint FK si no existe
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_CREDENCIALES_ADMIN') AND parent_object_id = OBJECT_ID(N'CREDENCIALES'))
BEGIN
    ALTER TABLE CREDENCIALES WITH CHECK ADD CONSTRAINT FK_CREDENCIALES_ADMIN FOREIGN KEY(id_admin)
    REFERENCES ADMINISTRADOR (id);
    ALTER TABLE CREDENCIALES CHECK CONSTRAINT FK_CREDENCIALES_ADMIN;
    PRINT 'Foreign Key FK_CREDENCIALES_ADMIN creada';
END
GO
