USE VOLUNTARIADOBD;
GO

IF OBJECT_ID('dbo.DISPONIBILIDAD', 'U') IS NOT NULL
BEGIN
    DROP TABLE dbo.DISPONIBILIDAD;
END
GO

CREATE TABLE dbo.DISPONIBILIDAD (
    CODVOL nvarchar(20) NOT NULL,
    DIA nvarchar(10) NOT NULL,
    NUM_HORAS int NOT NULL DEFAULT 0,
    CONSTRAINT PK_DISPONIBILIDAD PRIMARY KEY (CODVOL, DIA),
    CONSTRAINT FK_DISPONIBILIDAD_VOLUNTARIO FOREIGN KEY (CODVOL) REFERENCES VOLUNTARIO (CODVOL) ON DELETE CASCADE
);
GO
